name: Generate Snake

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: pranto78
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: actions/checkout@v3

      - name: Move files to output folder
        run: |
          mkdir -p output
          cp dist/github-contribution-grid-snake.svg output/
          cp dist/github-contribution-grid-snake-dark.svg output/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate snake"
          branch: output
